[package]
name = "webrtc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.8.0"
base64 = "0.22.1"
chrono = "0.4.38"
serde = { version = "1.0.203", features = ["derive"] }
actix = "0.13.5"
actix-web-actors = "4.3.0"
bytes = "1.6.0"
